DROP TABLE IF EXISTS grade CASCADE;
DROP TABLE IF EXISTS journal CASCADE;
DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS school_class CASCADE;
DROP TABLE IF EXISTS subject CASCADE;
DROP TABLE IF EXISTS teacher CASCADE;
DROP TABLE IF EXISTS parent CASCADE;
