DROP TABLE IF EXISTS grade CASCADE;
DROP TABLE IF EXISTS journal CASCADE;
DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS school_class CASCADE;
DROP TABLE IF EXISTS subject CASCADE;
DROP TABLE IF EXISTS teacher CASCADE;
DROP TABLE IF EXISTS parent CASCADE;

DROP SEQUENCE IF EXISTS grade_grade_id_seq CASCADE;
DROP SEQUENCE IF EXISTS journal_journal_id_seq CASCADE;
DROP SEQUENCE IF EXISTS student_student_id_seq CASCADE;
DROP SEQUENCE IF EXISTS school_class_class_id_seq CASCADE;
DROP SEQUENCE IF EXISTS subject_subject_id_seq CASCADE;
DROP SEQUENCE IF EXISTS teacher_teacher_id_seq CASCADE;
DROP SEQUENCE IF EXISTS parent_parent_id_seq CASCADE;
