"""change grade.grade type

Revision ID: 9f5036e59fa0
Revises: e8f664807402
Create Date: 2025-11-29 13:18:59.581435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5036e59fa0'
down_revision: Union[str, Sequence[str], None] = 'e8f664807402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_journal_id'), table_name='journal')
    op.drop_table('journal')
    op.alter_column('grade', 'grade',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grade', 'grade',
               existing_type=sa.Text(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.create_table('journal',
    sa.Column('journal_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade_list', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['school_class.class_id'], name=op.f('journal_class_id_fkey')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], name=op.f('journal_subject_id_fkey')),
    sa.PrimaryKeyConstraint('journal_id', name=op.f('journal_pkey'))
    )
    op.create_index(op.f('ix_journal_journal_id'), 'journal', ['journal_id'], unique=False)
    # ### end Alembic commands ###
